### PR TITLE
[NOISSUE] fix: Refactor Modal component

### PR DESCRIPTION
**Pull request by Msarawan**
Refactored Acceptor and Broker delete Modal component.

Screenshot from 2024-06-24 14-17-13

Screenshot from 2024-06-24 14-21-23

### CODE REVIEW

**Review by lavocatt — CHANGES_REQUESTED** [review]
The confirmation modal to delete the acceptor must also work for connectors:
image
The issue in the current proposal is that that text doesn't adapt to what is supposed to get deleted. This is a regression in behavior, can you fix it please?

**Comment by Msarawan** [comment]
> The confirmation modal to delete the acceptor must also work for connectors: image The issue in the current proposal is that that text doesn't adapt to what is supposed to get deleted. This is a regression in behavior, can you fix it please?

@lavocatt , means we need to display the selected acceptor/connectors name in the description message right as we were displaying in the brokers?

**Comment by Msarawan** [comment]
> > @lavocatt , means we need to display the selected acceptor/connectors name in the description message right as we were displaying in the brokers?
> 
> It means that the title should be: `Permanently delete the acceptor` when the user deletes an acceptor. And `Permanently delete the connector` when the user deletes a connector.
> 
> Look at the what the code was doing before your changes: image
> 
> The `subject` of the deletion was passed as a parameter. And was used in the title. Is it clearer?

yes Got it. i will update the PR. thanks!

**Review by lavocatt — APPROVED** [review]
Thanks for these changes! Good work!

**Pull request merged**
