### PR TITLE
[#147] Implementing Broker Creation form

### PR DESCRIPTION
**Pull request by gaohoward**

### CODE REVIEW

**Comment by lavocatt** [comment]
@howardgao I've rebased the work with the reducer and added it to you PR. Looking forward to hearing your thoughts about it :slightly_smiling_face:

**Comment by lavocatt** [comment]
I think we should merge this PR soon, wdyt @howardgao and @Msarawan ?

**Review by lavocatt — APPROVED** [review]
Thanks Howard for this work :rocket:

**Review by Msarawan — APPROVED** [review]
LGTM!! Good work @gaohoward  and @lavocatt!

**Pull request merged**
