### PR TITLE
[#198] the yaml editor allows to enter new Lines

### LINKED ISSUE #198: The yaml editor doesn't allow a user to add new lines
Try to add a new line in the yaml editor and you won't be able to.

### PR DESCRIPTION
**Pull request by lavocatt**
Previously the yaml editor wasn't allowing us to add new lines. This was because at each keystroke the yaml file was formated automatically, removing unecessary lines..
This meant that the user had to use tricks like copy&pasting to get to a state the wanted to have.

To fix that, this commits reverts back to using the resource editor provided by the console. It has several advantages:
* The use can edit the file as they want without bugs
* There's documentation included from the CRDs when hovering properties

The main drawback is that the user needs to click on save to save their changes to the model, then needs to click on apply to apply their config (either creating or updating)

fixes #198

### CODE REVIEW

**Comment by lavocatt** [comment]
This PR is currently blocked on https://issues.redhat.com/browse/OCPBUGS-38484

**Comment by lavocatt** [comment]
> This PR is currently blocked on https://issues.redhat.com/browse/OCPBUGS-38484

Upgrading to patternfly5 fixed the issue for us.

**Comment by Msarawan** [comment]
Hello @lavocatt , could you please rebase the branch with the main branch.

**Review by Msarawan — APPROVED** [review]
All LGTM. Good work Thomas.

**Pull request merged**
