### PR TITLE
[NOISSUE] allow custom certificate names

### PR DESCRIPTION
**Pull request by lavocatt**
Allow a user to override a certificate value for the acceptor if necessary.

### CODE REVIEW

**Review by gaohoward — DISMISSED** [review]

**Review by Msarawan — APPROVED** [review]

**Comment by Msarawan** [comment]
LGTM!

**Comment by lavocatt** [comment]
I'm not entirely sure if this feature is good to keep, what is your opinion @howardgao?

**Comment by gaohoward** [comment]
> I'm not entirely sure if this feature is good to keep, what is your opinion @howardgao?

Hi Thomas, I think this is a useful feature. It would be good to recognize secrets that have suffix like `-ptls`, because those kind of secrets are supported by operator. I know the PR is a generic one, can you make it at least make `-ptls` secrets in the select list?

**Comment by lavocatt** [comment]
Thanks @gaohoward I will work on an improvement after #174

**Review by gaohoward — APPROVED** [review]

**Pull request merged**
